backend:
  name: git-gateway
  branch: 'main'
  repo: 'KylerBesher/kaldi-test'

media_folder: "site/static/img" 
public_folder: "img"

collections:
  - name: "artists"
    label: "Artist"
    editor:
      preview: false
    folder: "site/content/artists"
    create: true
    fields:
      - {
          label: "Title",
          name: "title",
          widget: "string",
          hint: "This is what will show up in the url. eg truelovetattooks.com/artists/TITLE",
        }
      - { label: "First Name", name: "firstName", widget: "string" }
      - { label: "Last Name", name: "lastName", widget: "string" }
      - {
          label: "Individual Profile Image",
          name: "imageProfile",
          widget: "image",
          required: true,
        }
      - {
          label: "Color Homepage Image",
          name: "imageColor",
          widget: "image",
          required: true,
        }
      - {
          label: "B&W Homepage Image",
          name: "imageBw",
          widget: "image",
          required: true,
        }

      - {
          label: "Position",
          name: "position",
          widget: "select",
          options:
            [
              "Tattooer",
              "Piercer",
              "Tattoo Apprentice",
              "Piercing Apprentice",
              "Tattooer/Owner",
            ],
        }
      - {
          label: "Social",
          name: social,
          widget: list,
          max: 2,
          fields:
            [
              {
                label: "Type",
                name: "type",
                widget: select,
                options: ["icons-facebook", "icons-instagram"],
              },
              { label: "Link", name: "link", widget: string },
            ],
        }
      - {
          label: "Bio",
          name: bio,
          widget: object,

          fields:
            [
              {
                label: "Type",
                name: "type",
                widget: select,
                options: ["Tattooing", "Piercing", "Tattooing and Piercing"],
              },

              {
                label: "Since",
                name: "since",
                widget: number,
                value_type: "int",
              },
              { label: "Inspired", name: "inspired", widget: text },
              { label: "Specializes", name: "specializes", widget: text },
              { label: "First Tattoo", name: "firstTattoo", widget: text },
              { label: "Outside", name: "outside", widget: text },
            ],
        }

  - name: "pages"
    label: "Main Page"
    editor:
      preview: false
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - { label: Title, name: title, widget: hidden, default: "Home"}
          - { label: Video, name: video, widget: file, hint: Make sure that this is an MP4 file }

          - {
              label: "About True Love",
              name: blurb,
              widget: object,
              fields:
                [
                  { label: "Heading", name: "heading", widget: string },
                  { label: "Text", name: "text", widget: "text" },
                ],
            }
          - { label: Parallax Image 1, name: parallax1, widget: image }

          - {
              label: "Care Section",
              name: aftercare,
              widget: list,

              fields:
                [
                  {
                    label: "Type",
                    name: "type",
                    widget: select,
                    options: ["Tattoos", "Piercings"],
                  },
                  { label: "Is Hidden", name: "isDraft", widget: boolean },
                  {
                    label: "Sections",
                    name: sections,
                    widget: list,
                    fields:
                      [
                        { label: Heading, name: title, widget: string },
                        { label: Body, name: content, widget: markdown },
                      ],
                  },
                ],
            }
          - { label: Parallax Image 2, name: parallax2, widget: image }

          - {
              label: "Artists",
              name: artists,
              widget: object,
              fields:
                [
                  { label: "Heading", name: "heading", widget: string },
                  { label: "Text", name: "text", widget: "text" },
                ],
            }
          - { label: Parallax Image 3, name: parallax3, widget: image }
          - {
              label: "Faqs",
              name: faqs,
              widget: list,
              fields:
                [
                  { label: "Heading", name: "question", widget: string },
                  { label: "Content", name: "answer", widget: text },
                ],
            }
          - { label: Parallax Image 4, name: parallax4, widget: image }
          - { label: Shop info, name: info, widget: object, fields: 
                [
                  { label: "Street Address", name: "address", widget: string },
                  { label: "City", name: "city", widget: string },
                  { label: "State", name: "state", widget: string },
                  { label: "Zip Code", name: "zip", widget: number },
                  { label: "Phone Number", name: "phone", widget: string },
                  { label: "Logo Small", name: "logoSmall", widget: image },
                  { label: "Logo Big", name: "logoBig", widget: image },
                  { label: Hours, name: hours, widget: list, fields: 
                      [
                        { label: "Day Range", name: "day", widget: string },
                        { label: "Time Range", name: "times", widget: string },
                      ]
                  }  

                ]
            }  

          